---
- name: user and ssk key settings
  include_tasks: user-sshkey.yml
  when: user_task
  tags: [usersshkey]

- name: setting the hostname
  include_tasks: hostname.yml
  when: hostname_task
  tags: [hostname]

- name: fixing the dns resolution
  include_tasks: fixdns.yml
  when: fixdns_task
  tags: [fixdns]

- name: apt repo settings
  include_tasks: apt-setting.yml
  when: aptsettings_tasks
  tags: [aptrepo]

- name: upgrading packages and installing neccessary things
  include_tasks: pkgs.yml
  when: packageandupdate_task
  tags: [upgrade]

- name: installing docker
  include_tasks: docker.yml
  when: docker_task
  tags: [docker]

